/* Base de datos "Tienda" */
SELECT nombre FROM tienda.producto;
SELECT nombre, precio FROM tienda.producto;
SHOW COLUMNS FROM tienda.producto;
SELECT nombre, precio, precio * 1.10 FROM tienda.producto;
SELECT nombre as nombre_del_producto, precio as euros, precio * 1.10 as dolares_norteamericanos FROM tienda.producto;  
SELECT UPPER(nombre), precio FROM tienda.producto;
SELECT LOWER(nombre), precio FROM tienda.producto;
SELECT nombre, UPPER(SUBSTRING(nombre, 1,2)) FROM tienda.fabricante;
SELECT nombre, ROUND(precio) FROM tienda.producto;
SELECT nombre, TRUNCATE(precio, 0) FROM tienda.producto;
SELECT codigo_fabricante FROM tienda.producto;
SELECT DISTINCT codigo_fabricante FROM tienda.producto;
SELECT nombre FROM tienda.fabricante ORDER BY nombre ASC;
SELECT nombre FROM tienda.fabricante ORDER BY nombre DESC;
SELECT nombre FROM tienda.producto ORDER BY nombre ASC, precio DESC;
SELECT DISTINCT nombre FROM tienda.fabricante LIMIT 5;
SELECT * FROM tienda.fabricante LIMIT 2 OFFSET 3;
SELECT nombre, precio FROM tienda.producto ORDER BY precio ASC LIMIT 1;
SELECT nombre, precio FROM tienda.producto ORDER BY precio DESC LIMIT 1;
SELECT nombre FROM tienda.producto WHERE producto.codigo_fabricante = 2; 
SELECT producto.nombre, producto.precio, fabricante.nombre FROM tienda.producto INNER JOIN tienda.fabricante WHERE fabricante.codigo = producto.codigo_fabricante;
SELECT producto.nombre, producto.precio, fabricante.nombre FROM tienda.producto INNER JOIN tienda.fabricante WHERE fabricante.codigo = producto.codigo_fabricante ORDER BY fabricante.nombre ASC;
SELECT producto.codigo AS codigo_producto, producto.nombre AS nombre_producto, fabricante.codigo AS codigo_fabricante, fabricante.nombre AS nombre_fabricante FROM tienda.producto INNER JOIN tienda.fabricante WHERE fabricante.codigo = producto.codigo_fabricante;
SELECT producto.nombre AS producto, producto.precio, fabricante.nombre AS fabricante FROM tienda.producto INNER JOIN tienda.fabricante WHERE fabricante.codigo = producto.codigo_fabricante ORDER BY producto.precio ASC LIMIT 1;
SELECT producto.nombre AS producto, producto.precio, fabricante.nombre AS fabricante FROM tienda.producto INNER JOIN tienda.fabricante WHERE fabricante.codigo = producto.codigo_fabricante ORDER BY producto.precio DESC LIMIT 1;
SELECT producto.nombre AS producto FROM tienda.producto INNER JOIN tienda.fabricante WHERE producto.codigo_fabricante = fabricante.codigo AND fabricante.nombre = 'lenovo';
SELECT producto.nombre AS producto FROM tienda .producto INNER JOIN tienda.fabricante WHERE producto.codigo_fabricante = fabricante.codigo AND fabricante.nombre = 'crucial' and producto.precio > '200';
SELECT producto.nombre AS producto FROM tienda .producto INNER JOIN tienda.fabricante ON producto.codigo_fabricante = fabricante.codigo WHERE fabricante.nombre = 'asus' OR fabricante.nombre = 'Hewlett-Packard' OR fabricante.nombre = 'seagate';
SELECT producto.nombre AS producto FROM tienda .producto INNER JOIN tienda.fabricante WHERE producto.codigo_fabricante = fabricante.codigo AND fabricante.nombre IN ('asus','Hewlett-Packard','seagate');
SELECT producto.nombre, producto.precio FROM tienda.producto INNER JOIN tienda.fabricante ON producto.codigo_fabricante = fabricante.codigo WHERE LOWER(RIGHT(fabricante.nombre, 1)) = 'e';
SELECT producto.nombre, producto.precio FROM tienda.producto INNER JOIN tienda.fabricante ON producto.codigo_fabricante = fabricante.codigo WHERE fabricante.nombre LIKE '%w%';
SELECT producto.nombre, producto.precio, fabricante.nombre FROM tienda.producto INNER JOIN tienda.fabricante ON fabricante.codigo = producto.codigo_fabricante WHERE producto.precio >= '180' ORDER BY producto.precio DESC, producto.nombre ASC;
SELECT DISTINCT fabricante.codigo, fabricante.nombre FROM tienda.fabricante INNER JOIN tienda.producto WHERE fabricante.codigo = producto.codigo_fabricante;
SELECT fabricante.nombre AS fabricante, producto.nombre AS producto FROM tienda.fabricante LEFT JOIN tienda.producto ON fabricante.codigo = producto.codigo_fabricante;
SELECT fabricante.nombre FROM tienda.fabricante LEFT JOIN tienda.producto ON fabricante.codigo = producto.codigo_fabricante WHERE producto.codigo_fabricante IS NULL; 
/* Base de datos "Universidad" */
SELECT apellido1, apellido2, nombre FROM universidad.persona WHERE tipo = "alumno" ORDER BY apellido1 ASC, apellido2 ASC, nombre ASC;
SELECT nombre, apellido1, apellido2 FROM universidad.persona WHERE tipo = "alumno" AND telefono IS NULL OR telefono = "";
SELECT * FROM universidad.persona WHERE tipo = "alumno" AND YEAR(fecha_nacimiento) = 1999;
SELECT * FROM universidad.persona WHERE tipo = "profesor" AND (telefono IS NULL OR telefono = "") AND nif LIKE "%K";
SELECT nombre FROM universidad.asignatura WHERE cuatrimestre = 1 AND curso = 3 AND id_grado = 7;
SELECT persona.apellido1, persona.apellido2, persona.nombre, profesor.id_departamento FROM universidad.persona INNER JOIN universidad.profesor ON persona.id = profesor.id_profesor WHERE tipo = "profesor";
SELECT asignatura.nombre, curso_escolar.anyo_inicio, curso_escolar.anyo_fin FROM universidad.persona INNER JOIN universidad.alumno_se_matricula_asignatura ON alumno_se_matricula_asignatura.id_alumno = persona.id INNER JOIN universidad.asignatura ON alumno_se_matricula_asignatura.id_asignatura = asignatura.id INNER JOIN universidad.curso_escolar ON alumno_se_matricula_asignatura.id_curso_escolar = curso_escolar.id WHERE persona.nif = "26902806M";
SELECT DISTINCT departamento.nombre FROM universidad.departamento INNER JOIN universidad.profesor ON profesor.id_departamento = departamento.id INNER JOIN universidad.asignatura ON asignatura.id_profesor = profesor.id_profesor INNER JOIN universidad.grado ON grado.id = asignatura.id_grado WHERE grado.nombre = "Grado en Ingeniería Informática (Plan 2015)";
SELECT DISTINCT nombre, apellido1, apellido2 FROM universidad.persona INNER JOIN universidad.alumno_se_matricula_asignatura ON persona.id = alumno_se_matricula_asignatura.id_alumno INNER JOIN universidad.curso_escolar ON alumno_se_matricula_asignatura.id_curso_escolar = curso_escolar.id WHERE persona.tipo = "alumno" AND curso_escolar.anyo_inicio = 2018 AND curso_escolar.anyo_fin = 2019;
SELECT DISTINCT departamento.nombre, persona.apellido1, persona.apellido2, persona.nombre FROM universidad.persona LEFT JOIN universidad.profesor ON profesor.id_profesor = persona.id LEFT JOIN universidad.departamento ON departamento.id = profesor.id_departamento WHERE persona.tipo = "profesor" ORDER BY departamento.nombre ASC, persona.apellido1 ASC, persona.apellido2 ASC, persona.nombre ASC;
SELECT persona.apellido1, persona.apellido2, persona.nombre FROM universidad.persona LEFT JOIN universidad.profesor ON profesor.id_profesor = persona.id LEFT JOIN universidad.departamento ON departamento.id = profesor.id_departamento WHERE persona.tipo = "profesor" AND profesor.id_departamento IS NULL;
SELECT departamento.nombre FROM universidad.departamento LEFT JOIN universidad.profesor ON departamento.id = profesor.id_departamento WHERE profesor.id_departamento IS NULL;
SELECT persona.apellido1, persona.apellido2, persona.nombre FROM universidad.persona LEFT JOIN universidad.profesor ON profesor.id_profesor = persona.id LEFT JOIN universidad.asignatura ON profesor.id_profesor = asignatura.id_profesor WHERE persona.tipo = "profesor" AND asignatura.id_profesor IS NULL;
SELECT asignatura.nombre FROM universidad.asignatura LEFT JOIN universidad.profesor ON profesor.id_profesor = asignatura.id_profesor WHERE asignatura.id_profesor IS NULL;
SELECT DISTINCT departamento.nombre FROM universidad.departamento LEFT JOIN universidad.profesor ON profesor.id_departamento LEFT JOIN universidad.asignatura ON profesor.id_profesor = asignatura.id_profesor WHERE asignatura.curso IS NULL;
SELECT COUNT(*) AS numero_alumnos FROM universidad.persona WHERE tipo = "alumno";
SELECT COUNT(*) FROM universidad.persona WHERE tipo = "alumno" AND YEAR(fecha_nacimiento) = 1999;
SELECT departamento.nombre, COUNT(profesor.id_profesor) FROM universidad.departamento INNER JOIN universidad.profesor ON profesor.id_departamento = departamento.id INNER JOIN universidad.persona ON profesor.id_profesor = persona.id GROUP BY departamento.nombre HAVING COUNT(profesor.id_profesor) > 0 ORDER BY persona.nombre DESC;
SELECT departamento.nombre, COUNT(persona.nombre) FROM universidad.departamento LEFT JOIN universidad.profesor ON profesor.id_departamento = departamento.id LEFT JOIN universidad.persona ON profesor.id_profesor = persona.id GROUP BY departamento.nombre;
SELECT grado.nombre, COUNT(asignatura.id) FROM universidad.grado LEFT JOIN universidad.asignatura ON grado.id = asignatura.id_grado GROUP BY grado.nombre ORDER BY COUNT(asignatura.id) DESC;
SELECT grado.nombre, COUNT(asignatura.id) FROM universidad.grado INNER JOIN universidad.asignatura ON grado.id = asignatura.id_grado GROUP BY grado.nombre HAVING COUNT(asignatura.id) > 40;
SELECT grado.nombre, asignatura.nombre, SUM(asignatura.creditos) FROM universidad.grado INNER JOIN universidad.asignatura ON grado.id = asignatura.id_grado GROUP BY grado.nombre, asignatura.nombre;
SELECT curso_escolar.anyo_inicio, COUNT(alumno_se_matricula_asignatura.id_alumno) FROM universidad.curso_escolar LEFT JOIN universidad.alumno_se_matricula_asignatura ON curso_escolar.anyo_inicio = alumno_se_matricula_asignatura.id_curso_escolar GROUP BY curso_escolar.anyo_inicio;
SELECT persona.id, persona.nombre, persona.apellido1, persona.apellido2, COUNT(asignatura.id) FROM universidad.persona LEFT JOIN universidad.profesor ON persona.id = profesor.id_profesor LEFT JOIN universidad.asignatura ON profesor.id_profesor = asignatura.id_profesor GROUP BY persona.id, persona.nombre, persona.apellido1, persona.apellido2 ORDER BY COUNT(asignatura.id) DESC;
SELECT * FROM universidad.persona WHERE persona.tipo = "alumno" ORDER BY persona.fecha_nacimiento DESC LIMIT 1;
SELECT persona.id, persona.nombre, persona.apellido1 FROM universidad.persona INNER JOIN universidad.profesor ON persona.id = profesor.id_profesor LEFT JOIN universidad.asignatura ON profesor.id_profesor = asignatura.id_profesor INNER JOIN universidad.departamento ON profesor.id_departamento = departamento.id WHERE asignatura.id IS NULL;

